//There is currently no way to insert text to the very start of a file generated by 
//SWIG. This results in compile errors with Visual Studio.

//Begin dumb workaround.

#include "llviewerprecompiledheaders.h"
#include "LuaBase_wrap.cxx"
