gVisualParamList={
"big_brow",
"nose_big_out",
"broad_nostrils",
"cleft_chin",
"bulbous_nose_tip",
"weak_chin",
"double_chin",
"sunken_cheeks",
"noble_nose_bridge",
"jowls",
"cleft_chin_upper",
"high_cheek_bones",
"ears_out",
"pointy_eyebrows",
"square_jaw",
"puffy_upper_cheeks",
"upturned_nose_tip",
"bulbous_nose",
"upper_eyelid_fold",
"attached_earlobes",
"baggy_eyes",
"wide_eyes",
"wide_lip_cleft",
"lips_thin",
"wide_nose_bridge",
"lips_fat",
"wide_upper_lip",
"wide_lower_lip",
"arced_eyebrows",
"male_skeleton",
"height",
"thickness",
"big_ears",
"shoulders",
"hip width",
"torso length",
"male_head",
"old",
"furrowed_eyebrows",
"surprised_eyebrows",
"worried_eyebrows",
"frown_mouth",
"smile_mouth",
"blink_left",
"blink_right",
"lipsync_aah",
"lipsync_ooh",
"male",
"glove length",
"eye lightness",
"eye color",
"male_torso",
"hands_relaxed",
"hands_point",
"hands_fist",
"big_belly_torso",
"breast size",
"muscular_torso",
"rainbow color",
"red skin",
"pigment",
"rainbow color",
"red hair",
"blonde hair",
"white hair",
"rosy complexion",
"lip pinkness",
"wrinkles",
"eyebrow size",
"shading",
"shading",
"front fringe",
"side fringe",
"back fringe",
"hair front",
"hair sides",
"hair back",
"hair sweep",
"hair tilt",
"hair_part_middle",
"hair_part_right",
"hair_part_left",
"hair_sides_full",
"bangs_front_up",
"bangs_front_down",
"bangs_sides_up",
"bangs_sides_down",
"bangs_back_up",
"bangs_back_down",
"body definition",
"big_butt_legs",
"muscular_legs",
"male_legs",
"lip width",
"big_belly_legs",
"belly size",
"shading",
"shading",
"shading",
"shading",
"facial definition",
"wrinkles",
"freckles",
"sideburns",
"moustache",
"soulpatch",
"chin curtains",
"hair_front_down",
"hair_front_up",
"hair_sides_down",
"hair_sides_up",
"hair_back_down",
"hair_back_up",
"hair_rumpled",
"hair_swept_back",
"hair_swept_forward",
"hair_volume",
"hair_big_front",
"hair_big_top",
"hair_big_back",
"hair_spiked",
"deep_chin",
"egg_head",
"squash_stretch_head",
"square_head",
"round_head",
"hair_tilt_right",
"hair_tilt_left",
"bangs_part_middle",
"head shape",
"eye_spread",
"eyebone_spread",
"eye spacing",
"shoe_heels",
"heel height",
"express_closed_mouth",
"express_tongue_out",
"express_surprise_emote",
"express_wink_emote",
"express_embarrassed_emote",
"express_shrug_emote",
"express_kiss",
"express_bored_emote",
"express_repulsed_emote",
"express_disdain",
"express_afraid_emote",
"express_worry_emote",
"express_cry_emote",
"express_sad_emote",
"express_anger_emote",
"express_frown",
"express_laugh_emote",
"express_toothsmile",
"express_smile",
"displace_hair_facial",
"shoe_heel_height",
"shoe_platform_height",
"shoe_platform",
"platform height",
"lip thickness",
"mouth_height",
"breast_gravity",
"shoe_platform_width",
"shoe_heel_point",
"shoe_heel_thick",
"shoe_toe_point",
"shoe_toe_square",
"heel shape",
"toe shape",
"foot_size",
"displace_loose_lowerbody",
"wide_nose",
"eyelashes_long",
"sleeve length cloth",
"shirt bottom cloth",
"collar front height cloth",
"sleeve length",
"bottom",
"collar front",
"sleeve length",
"collar front",
"bottom length lower",
"open jacket",
"waist height cloth",
"pants length cloth",
"shoe height",
"socks length",
"pants length",
"bottom length upper",
"bottom length lower",
"open upper",
"open lower",
"pants waist",
"leg_pantflair",
"big_chest",
"small_chest",
"displace_loose_upperbody",
"forehead angle",
"forehead_round",
"forehead_slant",
"express_open_mouth",
"fat_head",
"fat_torso",
"fat_legs",
"body fat",
"low_crotch",
"hair_egg_head",
"hair_squash_stretch_head",
"hair_square_head",
"hair_round_head",
"hair_forehead_round",
"hair_forehead_slant",
"egg_head",
"squash_stretch_head",
"scrawny_torso",
"torso muscles",
"eyelid_corner_up",
"scrawny_legs",
"leg muscles",
"tall_lips",
"shoe_toe_thick",
"head size",
"crooked_nose",
"smile_mouth",
"frown_mouth",
"mouth corner",
"shear_head",
"eyebone_head_shear",
"face shear",
"shift_mouth",
"pop_eye",
"jaw_jut",
"hands_relaxed_l",
"hands_point_l",
"hands_fist_l",
"hands_relaxed_r",
"hands_point_r",
"hands_fist_r",
"hands_typing",
"hair_shear_back",
"hand size",
"love_handles",
"scrawny_torso_male",
"torso muscles",
"eyeball_size",
"eyeball_size",
"eyeball_size",
"head size",
"neck thickness",
"breast_female_cleavage",
"chest_male_no_pecs",
"head_eyes_big",
"eyeball_size",
"eyeball_size",
"eyebone_big_eyes",
"eye size",
"eyeball_size",
"leg length",
"arm length",
"eyeball_size",
"eyeball_size",
"lipstick color",
"lipstick",
"lipgloss",
"eyeliner",
"blush",
"blush color",
"out shdw opacity",
"outer shadow",
"out shdw color",
"inner shadow",
"nail polish",
"blush opacity",
"in shdw color",
"in shdw opacity",
"eyeliner color",
"nail polish color",
"eyebrow density",
"5 o'clock shadow",
"hair thickness",
"saddlebags",
"hair_taper_back",
"hair_taper_front",
"neck length",
"lower_eyebrows",
"lower_bridge_nose",
"low_septum_nose",
"jaw_angle",
"hair_volume_small",
"hair_shear_front",
"hair volume",
"lip_cleft_deep",
"puffy_lower_lids",
"hands_salute_r",
"bug_eyed_head",
"eyebone_bug",
"eye depth",
"elongate_head",
"elongate_head_hair",
"eyebone_head_elongate",
"head length",
"shear_head_hair",
"body freckles",
"freckles upper",
"freckles lower",
"collar back height cloth",
"collar back",
"collar back",
"collar back",
"hair_pigtails_short",
"hair_pigtails_med",
"hair_pigtails_long",
"pigtails",
"hair_ponytail_short",
"hair_ponytail_med",
"hair_ponytail_long",
"ponytail",
"hair_pigtails_medlong",
"hands_peace_r",
"hands_spread_r",
"leg_longcuffs",
"small_butt",
"butt size",
"pointy_ears",
"fat_upper_lip",
"fat_lower_lip",
"lip ratio",
"sleeve length",
"shirt bottom",
"collar front",
"shirt_red",
"shirt_green",
"shirt_blue",
"pants_red",
"pants_green",
"pants_blue",
"lower_jacket_red",
"lower_jacket_green",
"lower_jacket_blue",
"shoes_red",
"shoes_green",
"waist height",
"pants length",
"loose lower clothing",
"shoes_blue",
"socks_red",
"socks_green",
"socks_blue",
"undershirt_red",
"undershirt_green",
"undershirt_blue",
"underpants_red",
"underpants_green",
"underpants_blue",
"gloves_red",
"loose upper clothing",
"gloves_green",
"gloves_blue",
"upper_jacket_red",
"upper_jacket_green",
"upper_jacket_blue",
"jacket_red",
"jacket_green",
"jacket_blue",
"shirtsleeve_flair",
"bowed_legs",
"hip length",
"no_chest",
"glove fingers",
"skirt_poofy",
"skirt_loose",
"skirt_bowlegs",
"skirt_bustle",
"skirt_belly",
"skirt_saddlebags",
"skirt_chubby",
"skirt_bigbutt",
"bowed_legs",
"saddlebags",
"love_handles",
"skirt_lovehandles",
"skirt_male",
"skirt length",
"slit front",
"slit back",
"slit left",
"slit right",
"skirt_looseness",
"skirt_tight",
"skirt_smallbutt",
"shirt wrinkles",
"pants wrinkles",
"pointy_eyebrows",
"lower_eyebrows",
"arced_eyebrows",
"bump base",
"bump upperdef",
"jacket upper wrinkles",
"jacket upper wrinkles",
"jacket wrinkles",
"bump upperdef",
"male_package",
"eyelid_inner_corner_up",
"upper clothes shading",
"sleeve length shadow",
"shirt shadow bottom",
"collar front shadow height",
"collar back shadow height",
"lower clothes shading",
"waist height shadow",
"pants length shadow",
"skirt_red",
"skirt_green",
"skirt_blue",
"eyebrow size bump",
"eyebrow size",
"eyebrow density bump",
"eyebrow density",
"sideburns bump",
"sideburns",
"moustache bump",
"moustache",
"soulpatch bump",
"soulpatch",
"chin curtains bump",
"chin curtains",
"5 o'clock shadow bump",
"sleeve length cloth",
"shirt bottom cloth",
"collar front height cloth",
"collar back height cloth",
"waist height cloth",
"pants length cloth",
"jacket sleeve length bump",
"jacket sleeve length",
"jacket collar front bump",
"jacket collar front",
"jacket collar back bump",
"jacket collar back",
"jacket bottom length upper bump",
"jacket open upper bump",
"jacket bottom length lower bump",
"jacket open lower bump",
"sleeve length cloth",
"shirt bottom cloth",
"collar front height cloth",
"collar back height cloth",
"jacket bottom length lower bump",
"jacket open lower bump",
"waist height cloth",
"pants length cloth",
"jacket bottom length upper bump",
"jacket open upper bump",
"jacket sleeve length bump",
"jacket collar front bump",
"jacket collar back bump",
"sleeve length",
"sleeve length bump",
"bottom",
"bottom bump",
"collar front",
"collar front bump",
"collar back",
"collar back bump",
"socks length bump",
"socks length bump",
"shoe height",
"shoe height bump",
"pants length",
"pants length",
"pants waist",
"pants waist",
"glove length",
"glove length bump",
"glove fingers",
"glove fingers bump"
}
