-- AUTOMATICALLY GENERATED BY scripts/GetHooks.lua! DO NOT MODIFY! --


-- defined in indra/newview/LunaLua.cpp:191
RegisterHook("OnLunaInit"	,"Luna's Lua engine has initialized.")

-- defined in indra/newview/llfloaterbump.cpp:165
RegisterHook("OnBump"	,"You were bumped by something")

-- defined in indra/newview/llviewermessage.cpp:2926
RegisterHook("OnBridgeCommand"	,"Triggered when an object tries to communicate via the debug channel or the llOwnerSay channel using a command prefixed with &FLEXLIFE;")

-- defined in indra/newview/llvoavatar.cpp:5415
RegisterHook("OnAnimStop"	,"For AOs.")

-- defined in indra/newview/llviewermessage.cpp:2932
RegisterHook("OnChatSay"	,"Triggered when an object uses llOwnerSay.")

-- defined in indra/newview/llviewerwindow.cpp:617
RegisterHook("OnLeftMouseDown"	,"Left mouse button is DOWN.")

-- defined in indra/newview/llviewermessage.cpp:2958
RegisterHook("OnChatUnknown"	,"Triggered when someone uses an unknown chat method.")

-- defined in indra/newview/llvoavatar.cpp:3085
RegisterHook("OnAvatarLoading"	,"Trigger loading effect plugin :V")

-- defined in indra/newview/llviewerobject.cpp:1022
RegisterHook("OnSetText"	,"Someone set this object's llSetText.")

-- defined in indra/newview/llagent.cpp:838
RegisterHook("OnPhantom"	,"Tells the script engine whether a user has become phantom.")

-- defined in indra/newview/llviewerwindow.cpp:2401
RegisterHook("PostUIDraw"	,"Do GL stuff before drawing the UI. (BLOCKING)")

-- defined in indra/newview/llvoavatar.cpp:5348
RegisterHook("OnAnimStart"	,"For AOs.")

-- defined in indra/newview/llagent.cpp:966
RegisterHook("OnRegionChanged"	,"Tells Lua that you have moved into a new region.")

-- defined in indra/newview/llvoavatar.cpp:3080
RegisterHook("OnAvatarLoaded"	,"Triggered when an avatar has been fully loaded.")

-- defined in indra/newview/llviewerobject.cpp:4269
RegisterHook("OnAttachedParticles"	,"Particle data.")

-- defined in indra/newview/llviewerobject.cpp:4395
RegisterHook("OnAttachedSound"	,"Object playing a sound (includes looped sounds).")

-- defined in indra/newview/llvoavatar.cpp:6541
RegisterHook("OnAttach"	,"Object UUID has attached to avatar Name.")

-- defined in indra/newview/llviewerobjectlist.cpp:1412
RegisterHook("OnObjectCreated"	,"An object has rezzed/appeared.")

-- defined in indra/newview/llviewermessage.cpp:2916
RegisterHook("OnChatWhisper"	,"Triggered when someone whispers something in local chat")

-- defined in indra/newview/llviewerwindow.cpp:726
RegisterHook("OnDoubleClick"	,"Right mouse button is DOWN.")

-- defined in indra/newview/llviewermessage.cpp:2950
RegisterHook("OnChatShout"	,"Triggered when someone shouts something in local chat.")

-- defined in indra/newview/llviewermessage.cpp:4046
RegisterHook("OnSoundTriggered"	,"Triggered when a sound is triggered.")

-- defined in indra/newview/llviewermessage.cpp:2937
RegisterHook("OnChatDebug"	,"Triggered when an object states something on the debug channel.")

-- defined in indra/newview/llviewerwindow.cpp:1266
RegisterHook("OnKeyDown"	,"Right mouse button is DOWN.")

-- defined in indra/newview/llviewerwindow.cpp:907
RegisterHook("OnRightMouseDown"	,"Right mouse button is DOWN.")

-- defined in indra/newview/llagent.cpp:504
RegisterHook("OnAgentInit"	,"On login, tells the Lua engine the name of the user and whether it's a Linden or not.")

-- defined in indra/newview/llviewerwindow.cpp:811
RegisterHook("OnLeftMouseUp"	,"Left mouse button is UP.")

-- defined in indra/newview/LuaInventory_f.cpp:261
RegisterHook("OnAssetDownloaded"	,"Asset successfully downloaded.")

-- defined in indra/newview/llviewerwindow.cpp:1019
RegisterHook("OnRightMouseUp"	,"Right mouse button is UP.")

-- defined in indra/newview/LuaInventory_f.cpp:267
RegisterHook("OnAssetFailed"	,"Asset failed to download or decode.")

-- defined in indra/newview/llviewerwindow.cpp:1123
RegisterHook("OnMiddleMouseUp"	,"Middle mouse button is Up.")

-- defined in indra/newview/llviewerwindow.cpp:1200
RegisterHook("OnWindowResized"	,"Window was resized.")
